language: perl
perl:     5.20
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libluajit-5.1-dev
      - libluajit-5.1.2

env:
  global:
    - LUAJIT_LIB=/usr/lib/x86_64-linux-gnu/
    - LUAJIT_INC=/usr/include/luajit-2.0/
    - VER_LUA_NGINX=0.9.16
    - VER_NGX_DEVEL=0.2.19
  matrix:
    - VER_NGINX=1.6.3
    - VER_NGINX=1.8.0
    - VER_NGINX=1.9.5

before_install:
  - git submodule init
  - git submodule update

before_script:
 - chmod +x compile_test.sh

install: cpanm -v --notest Test::Nginx
script:  ./compile_test.sh

notifications:
    on_success: never
    on_failure: never