language: perl
perl: 5.19

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq libluajit-5.1-dev libluajit-5.1.2
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

install:
  - mkdir ./vendor && cd ./vendor

  - wget http://nginx.org/download/nginx-1.6.0.tar.gz && tar -xf nginx-1.6.0.tar.gz

  - wget https://github.com/openresty/lua-nginx-module/archive/v0.9.7.tar.gz -O lua-nginx-module-0.9.7.tar.gz && tar -xf lua-nginx-module-0.9.7.tar.gz
  - wget https://github.com/sass/libsass/archive/3.0.tar.gz -O libsass-3.0.tar.gz && tar -xf libsass-3.0.tar.gz
  - wget https://github.com/simpl/ngx_devel_kit/archive/v0.2.19.tar.gz -O ngx-devel-kit-0.2.19.tar.gz && tar -xf ngx-devel-kit-0.2.19.tar.gz

  - cd ./libsass-3.0
  - sudo make install install-shared
  - sudo ldconfig
  - sudo cp sass.h sass_interface.h sass2scss.h /usr/include/

  - cd ../nginx-1.6.0
  - export LUAJIT_LIB=/usr/lib/x86_64-linux-gnu/
  - export LUAJIT_INC=/usr/include/luajit-2.0/
  - ./configure --add-module=../ngx_devel_kit-0.2.19 --add-module=../lua-nginx-module-0.9.7 --add-module=../../
  - sudo make install
  - export PATH=$PATH:/usr/local/nginx/sbin

  - cpanm -v --notest Test::Nginx

script: cd ${TRAVIS_BUILD_DIR} && prove
